### ISSUE TITLE
一个有关魈下落动作的问题

### ISSUE THREAD

**Issue by HastumeM** [ChaozhongLiu/DyberPet_GenshinImpact#11]
作者大大你好！我想问一下魈的下落动作还会进行更改吗？就是我感觉2D的下落看起来感觉有点......不自然？就感觉好像太快了，下落后恢复正常看着也有点快了。如果是3D就好了，或许看着自然一些
开了游戏找到我二十抽（欸嘿）出来的魈比对了一下，游戏内下落攻击时转的会慢一些，大招则是直接化成光然后快速下落，感觉也没转很快，只是转了一点点（下落前对比下落后面向位置）

**Comment by HastumeM** [comment]
感觉还是转的太快了，并且因为是2D看着不自然，是否可以改成跟大招一样的快速下落？

**Comment by HastumeM** [comment]
另外魈是有微笑的（啊啊啊他心里有我呜呜呜）感觉不太符合游戏经历？是否可以改成根据好感度变化？低于一个数值时没有太多表情，只有达到或者高于才有微笑，还是已经有了吗？（五级快六级了）

**Comment by ChaozhongLiu** [comment]
关于下落的问题，画师说她会修改的～ 再等等就好啦

关于动作，确实是根据好感度解锁的，你已经五六级了应该是所有的都解锁了。我们可以考虑重新设计一下解锁的顺序，感谢你！

**Comment by HastumeM** [comment]
不好意思但我指的不是动作，就是换成魈的时候无论好感度多少他脸上都总有笑容？不是说不好啦，就是感觉可以改成四五级以下没有笑容，只是平淡的脸，然后六七级好感度高了之后魈就会带着笑容？

**Comment by ChaozhongLiu** [comment]
哦哦明白了~ 确实可以实现 需要改代码和加新素材
等到这个需求会更广泛的时候就增加进去！

**Comment by HastumeM** [comment]
话说起来作者大大有考虑给data数据加密一下吗？就让数据不那么容易修改，我翻了一下发现数据是全透明的，我甚至可以改一下然后就有大量食物好感什么的（我不是我没有改我只是好奇）

**Comment by ChaozhongLiu** [comment]
哈哈哈哈哈哈 想过 但觉得大家随便怎么玩都好 我们也不赚钱不怎样 都无所谓啦

**Comment by HastumeM** [comment]
hhh好吧如果有时间我可以试试翻译一下来个英文版，看看能不能扩展用户（乐）
