### ISSUE TITLE
只能在第一个屏幕上活动

### ISSUE THREAD

**Issue by Cirno-NULL** [ChaozhongLiu/DyberPet_GenshinImpact#4]
# 问题出现环境
版本：Windows 10 
版本号：21H2 
操作系统内部版本：19044.2486
设备：**`双屏`**（接入多个显示器）
![image](https://user-images.githubusercontent.com/41545185/215242094-04e51049-00f0-4cfb-b633-08cee44a412d.png)

# 复现步骤
拖动到第二个屏幕任意位置
松开鼠标

#实际结果
操作完成后会瞬移到第一个屏幕边界处

# 预期结果
可以将宠物拖动到第二个屏幕上

**Comment by ChaozhongLiu** [comment]
现在确实没有考虑双屏的问题，有解决方案后会尽快更新

**Comment by ChaozhongLiu** [comment]
今天 v0.1.16 版本的更新已经全面支持多屏操作。
Issue 会继续保留一段时间，可以把遇到的问题反馈在这里。谢谢！

**Comment by ChaozhongLiu** [comment]
暂时没有遇到问题，之后有问题会重新开放。
