### ISSUE TITLE
报告一个“特性”【Dog】

### ISSUE THREAD

**Issue by LuiKlee** [ChaozhongLiu/DyberPet_GenshinImpact#6]
【win7】太过用力的话会在屏幕边缘卡很久，掉不下来

如图↓

![截图](https://user-images.githubusercontent.com/122352174/216250050-5ed1c246-e133-43e3-83a0-472830753541.PNG)

**Comment by LuiKlee** [comment]
版本0.1.16

**Comment by ChaozhongLiu** [comment]
嗯会这样，程序内部在疯狂计算速度的变化，因为向上的速度太快，重力加速度太小，所以会一直等到y轴速度降到0才会掉下来。
最好的办法是再拖拽她一下把她从角落救出来 23333 算是真 · 特性 hhhhhh

**Comment by ChaozhongLiu** [comment]
不过倒是可以在到达边界的时候让速度归零，不过我在考虑要不要改嘞， 这样看着也挺好玩的2333
